// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindIdRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindIdRequest) Reset()         { *m = FindIdRequest{} }
func (m *FindIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindIdRequest) ProtoMessage()    {}
func (*FindIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *FindIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindIdRequest.Unmarshal(m, b)
}
func (m *FindIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindIdRequest.Marshal(b, m, deterministic)
}
func (m *FindIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindIdRequest.Merge(m, src)
}
func (m *FindIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindIdRequest.Size(m)
}
func (m *FindIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindIdRequest proto.InternalMessageInfo

func (m *FindIdRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type FindIdResponse struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindIdResponse) Reset()         { *m = FindIdResponse{} }
func (m *FindIdResponse) String() string { return proto.CompactTextString(m) }
func (*FindIdResponse) ProtoMessage()    {}
func (*FindIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *FindIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindIdResponse.Unmarshal(m, b)
}
func (m *FindIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindIdResponse.Marshal(b, m, deterministic)
}
func (m *FindIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindIdResponse.Merge(m, src)
}
func (m *FindIdResponse) XXX_Size() int {
	return xxx_messageInfo_FindIdResponse.Size(m)
}
func (m *FindIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindIdResponse proto.InternalMessageInfo

func (m *FindIdResponse) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type IdsAndPathsListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdsAndPathsListRequest) Reset()         { *m = IdsAndPathsListRequest{} }
func (m *IdsAndPathsListRequest) String() string { return proto.CompactTextString(m) }
func (*IdsAndPathsListRequest) ProtoMessage()    {}
func (*IdsAndPathsListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *IdsAndPathsListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdsAndPathsListRequest.Unmarshal(m, b)
}
func (m *IdsAndPathsListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdsAndPathsListRequest.Marshal(b, m, deterministic)
}
func (m *IdsAndPathsListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdsAndPathsListRequest.Merge(m, src)
}
func (m *IdsAndPathsListRequest) XXX_Size() int {
	return xxx_messageInfo_IdsAndPathsListRequest.Size(m)
}
func (m *IdsAndPathsListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdsAndPathsListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdsAndPathsListRequest proto.InternalMessageInfo

type IdsAndPathsResponse struct {
	Ids                  []int32  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Paths                []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdsAndPathsResponse) Reset()         { *m = IdsAndPathsResponse{} }
func (m *IdsAndPathsResponse) String() string { return proto.CompactTextString(m) }
func (*IdsAndPathsResponse) ProtoMessage()    {}
func (*IdsAndPathsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *IdsAndPathsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdsAndPathsResponse.Unmarshal(m, b)
}
func (m *IdsAndPathsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdsAndPathsResponse.Marshal(b, m, deterministic)
}
func (m *IdsAndPathsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdsAndPathsResponse.Merge(m, src)
}
func (m *IdsAndPathsResponse) XXX_Size() int {
	return xxx_messageInfo_IdsAndPathsResponse.Size(m)
}
func (m *IdsAndPathsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IdsAndPathsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IdsAndPathsResponse proto.InternalMessageInfo

func (m *IdsAndPathsResponse) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *IdsAndPathsResponse) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type AuthorizationCheckRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationCheckRequest) Reset()         { *m = AuthorizationCheckRequest{} }
func (m *AuthorizationCheckRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorizationCheckRequest) ProtoMessage()    {}
func (*AuthorizationCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *AuthorizationCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationCheckRequest.Unmarshal(m, b)
}
func (m *AuthorizationCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationCheckRequest.Marshal(b, m, deterministic)
}
func (m *AuthorizationCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationCheckRequest.Merge(m, src)
}
func (m *AuthorizationCheckRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorizationCheckRequest.Size(m)
}
func (m *AuthorizationCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationCheckRequest proto.InternalMessageInfo

func (m *AuthorizationCheckRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type AuthorizationCheckResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationCheckResponse) Reset()         { *m = AuthorizationCheckResponse{} }
func (m *AuthorizationCheckResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorizationCheckResponse) ProtoMessage()    {}
func (*AuthorizationCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *AuthorizationCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationCheckResponse.Unmarshal(m, b)
}
func (m *AuthorizationCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationCheckResponse.Marshal(b, m, deterministic)
}
func (m *AuthorizationCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationCheckResponse.Merge(m, src)
}
func (m *AuthorizationCheckResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorizationCheckResponse.Size(m)
}
func (m *AuthorizationCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationCheckResponse proto.InternalMessageInfo

func (m *AuthorizationCheckResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*FindIdRequest)(nil), "auth.FindIdRequest")
	proto.RegisterType((*FindIdResponse)(nil), "auth.FindIdResponse")
	proto.RegisterType((*IdsAndPathsListRequest)(nil), "auth.IdsAndPathsListRequest")
	proto.RegisterType((*IdsAndPathsResponse)(nil), "auth.IdsAndPathsResponse")
	proto.RegisterType((*AuthorizationCheckRequest)(nil), "auth.AuthorizationCheckRequest")
	proto.RegisterType((*AuthorizationCheckResponse)(nil), "auth.AuthorizationCheckResponse")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xad, 0xb5, 0xd3, 0x3e, 0xd8, 0x18, 0xd9, 0x28, 0x5d, 0x11, 0xac, 0x39, 0x48, 0x2f,
	0x56, 0xd0, 0x5d, 0x3d, 0x4c, 0xc1, 0x51, 0xf4, 0x20, 0xf1, 0x26, 0x78, 0xa8, 0x26, 0xd0, 0xa0,
	0xb4, 0x75, 0x79, 0xf5, 0xe0, 0x7f, 0xed, 0x7f, 0x20, 0x49, 0xba, 0xb1, 0xb2, 0xf5, 0xf6, 0x5e,
	0xde, 0xef, 0xfb, 0xf2, 0xf2, 0x11, 0x80, 0xbc, 0xc1, 0x22, 0xad, 0x57, 0x15, 0x56, 0xe4, 0x48,
	0xd7, 0xf4, 0x1c, 0x86, 0x0f, 0xb2, 0xe4, 0x19, 0x67, 0xe2, 0xbb, 0x11, 0x0a, 0xc9, 0x18, 0x5c,
	0x25, 0x79, 0xe8, 0xc4, 0x4e, 0xe2, 0x33, 0x5d, 0xd2, 0x0b, 0x18, 0xad, 0x11, 0x55, 0x57, 0xa5,
	0x12, 0x64, 0x0a, 0xde, 0x4f, 0xfe, 0xd5, 0x08, 0x43, 0xb9, 0xcc, 0x36, 0x34, 0x84, 0x20, 0xe3,
	0x6a, 0x51, 0xf2, 0xe7, 0x1c, 0x0b, 0xf5, 0x24, 0x15, 0xb6, 0x9e, 0xf4, 0x16, 0x26, 0x5b, 0x93,
	0x8d, 0xcd, 0x18, 0x5c, 0xc9, 0x55, 0xe8, 0xc4, 0x6e, 0xe2, 0x31, 0x5d, 0x6a, 0xe3, 0x5a, 0x23,
	0xe1, 0x61, 0xec, 0x26, 0x3e, 0xb3, 0x0d, 0xbd, 0x84, 0xd9, 0xa2, 0xc1, 0xa2, 0x5a, 0xc9, 0xdf,
	0x1c, 0x65, 0x55, 0xde, 0x17, 0xe2, 0xe3, 0xb3, 0x7f, 0xdf, 0x39, 0x44, 0xfb, 0xf0, 0xf6, 0xd2,
	0x00, 0x06, 0x0a, 0x73, 0x6c, 0x94, 0x91, 0x9c, 0xb0, 0xb6, 0xbb, 0xfe, 0x73, 0x60, 0xd8, 0x91,
	0x91, 0x39, 0x78, 0x4b, 0x81, 0x19, 0x27, 0x93, 0xd4, 0xc4, 0xd6, 0xc9, 0x29, 0x9a, 0x76, 0x0f,
	0xad, 0x3b, 0x3d, 0x20, 0x8f, 0x30, 0x32, 0xaa, 0xcd, 0x73, 0xc9, 0xa9, 0x25, 0xf7, 0x67, 0x13,
	0xcd, 0x76, 0xa6, 0x5b, 0x66, 0x6f, 0x10, 0x2c, 0x05, 0x76, 0xd6, 0x7a, 0x31, 0xeb, 0x92, 0x33,
	0x2b, 0xeb, 0xcd, 0x25, 0x8a, 0xfb, 0x81, 0xb5, 0xfd, 0x9d, 0xff, 0x7a, 0x9c, 0xa6, 0x57, 0x9a,
	0x7b, 0x1f, 0x98, 0x4f, 0x71, 0xf3, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xda, 0xf9, 0x57, 0x22,
	0x02, 0x00, 0x00,
}
