name: CI_RUN_TESTS

on:
  push:
    branches:
      - '**'

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21'

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          skip-cache: true

  tests:
    runs-on: ubuntu-latest
    needs: [ lint-check ]

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21'

      - name: Test
        run: go test ./...
        